fail_fast: true

repos:
  - repo: local
    hooks:
      - id: pylint
        name: Local PyLint
        language: system
        require_serial: true
        types:
          - python
        exclude: "^[^/]*env/|dev-[^/]*/"
        entry: pylint -j 0
      - id: mypy
        name: Local MyPy
        language: system
        types:
          - python
#        files: \.py$
        exclude: "^[^/]*env/|dev-[^/]*/"
        require_serial: true
#        entry: ./basic-installer.bash mypy --strict
        entry: mypy --strict --show-error-codes --no-warn-unused-ignores
# Main problem: python executable path, used to find the environment is hard
#  - repo: https://github.com/pre-commit/mirrors-mypy.git
#    rev: v1.2.0
#    hooks:
#      - id: mypy
#        exclude: "^[^/]*env/|dev-[^/]*/"
#        require_serial: true
#        args: [--strict, --show-error-codes, --no-warn-unused-ignores, --python-executable, .pyWEenv/bin/python]
#  - repo: meta
  - repo: https://github.com/inab/python-extended-json-schema-validator.git
    rev: v0.13.0
    hooks:
#      - id: identity
      - id: jsonschema_dir_validate
        name: Check jsonschema
        types:
          - json
        files: ^wfexs_backend/schemas/.*\.json$
        require_serial: true
        pass_filenames: false
        args: [ wfexs_backend/schemas ]

  - repo: https://github.com/jmfernandez/pre-commit_mirrors-actionlint.git
    rev: v1.6.24
    hooks:
      - id: actionlint

  - repo: https://github.com/ambv/black.git
    rev: 23.3.0
    hooks:
      - id: black
        exclude: "^[^/]*env/|dev-[^/]*/"
        args: [--diff, --check]

  - repo: local
    hooks:
      - id: citation.cff
        name: CITATION.CFF checker
        always_run: true
        pass_filenames: false
        language: system
        files: "CITATION.cff$"
#        entry: ./basic-installer.bash python dev-scripts/cff-ver-validate.py CITATION.cff
        entry: python dev-scripts/cff-ver-validate.py CITATION.cff
