fail_fast: true

repos:
  - repo: https://github.com/PyCQA/pylint
    rev: v2.15.2
    hooks:
      - id: pylint
        args: [--disable=all, --enable=unused-import]

  - repo: local
    hooks:
      - id: mypy
        name: Local MyPy
        language: system
        types: [file, python]
#        files: \.py$
        exclude: "^[^/]*env/"
        require_serial: true
        entry: ./basic-installer.bash mypy --strict

  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [--diff, --check]

