fail_fast: true

repos:
  - repo: https://github.com/PyCQA/pylint
    rev: v2.15.2
    hooks:
      - id: pylint
        require_serial: true
        args: [ -j, "0", --disable=all, --enable=unused-import, --fail-on=unused-import ]

  - repo: local
    hooks:
      - id: mypy
        name: Local MyPy
        language: system
        types: [file, python]
#        files: \.py$
        exclude: "^[^/]*env/|dev-[^/]*/"
        require_serial: true
#        entry: ./basic-installer.bash mypy --strict
        entry: mypy --strict --show-error-codes --no-warn-unused-ignores
    
#  - repo: meta
  - repo: https://github.com/inab/python-extended-json-schema-validator.git
    rev: v0.11.0
    hooks:
#      - id: identity
      - id: jsonschema_dir_validate
        name: Check jsonschema
        types:
          - directory
        files: ^wfexs_backend/schemas$
        require_serial: true

  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
        exclude: "^[^/]*env/|dev-[^/]*/"
        args: [--diff, --check]

  - repo: local
    hooks:
      - id: citation.cff
        name: CITATION.CFF checker
        always_run: true
        pass_filenames: false
        language: system
        files: "CITATION.cff$"
#        entry: ./basic-installer.bash python dev-scripts/cff-ver-validate.py CITATION.cff
        entry: python dev-scripts/cff-ver-validate.py CITATION.cff
