fail_fast: true

repos:
  - repo: https://github.com/PyCQA/pylint
    rev: v2.15.2
    hooks:
      - id: pylint
        args: [--disable=all, --enable=unused-import]

  - repo: local
    hooks:
      - id: mypy
        name: Local MyPy
        language: system
        types: [file, python]
#        files: \.py$
        exclude: "^[^/]*env/|dev-[^/]*/"
        require_serial: true
        entry: mypy --strict

  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
        exclude: "^[^/]*env/|dev-[^/]*/"
        args: [--diff, --check]

  - repo: local
    hooks:
      - id: citation.cff
        name: CITATION.CFF checker
        always_run: true
        language: system
        files: "^CITATION.cff$"
        entry: python dev-scripts/cff-ver-validate.py
