name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
    name: Pre-commit python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          architecture: x64
      - run: pip install wheel
      - run: pip install -r requirements.txt -r dev-requirements.txt -r mypy-requirements.txt
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all -c .pre-commit-config-gh.yaml
  pre-commit_3-6:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.6" ]
    name: Pre-commit python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          architecture: x64
      - run: pip install wheel
      - run: pip install -r requirements.txt -r requirements-additional-3.6.txt -r dev-requirements.txt -r mypy-requirements.txt
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all -c .pre-commit-config-gh-3.6.yaml
